### ISSUE TITLE
credential manifest and presentation exchange attachments 

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/edge-adapter#222]
Have below concerns over [credential manifest RFC](https://github.com/hyperledger/aries-rfcs/blob/master/features/0511-dif-cred-manifest-attach/README.md) : 

- need more clarification on use of domain & challenge in [offer-credential  attachment](https://github.com/hyperledger/aries-rfcs/blob/master/features/0511-dif-cred-manifest-attach/README.md#offer-credential-attachment-format) : 
Ex: Issuer can send offer-credential message to holder anytime whenever it there is an update (or new) in credential type it is supporting. Not sure how domain & challenge can help in this case. 
Also, credential preview from issuer could have helped more that manifest.
-

**Comment by llorllale** [comment]
@sudeshrshetty I left notes at https://github.com/hyperledger/aries-framework-go/issues/2065#issuecomment-666622298 that I think resolve the doubts about domain & challenge.

As for "credential preview" - the examples in RFC0511 just show how attachments work using the DIF's credential manifest format and have no say in whether `credential_preview` is included or not because that field is defined in the parent [RFC0453](https://github.com/hyperledger/aries-rfcs/blob/master/features/0453-issue-credential-v2/README.md).

Can we close this?

**Comment by sudeshrshetty** [comment]
@llorllale thanks, I am closing this
